# Generated by Django 4.1.1 on 2023-08-30 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartName', models.CharField(max_length=64, verbose_name='机构名称')),
                ('DepartCode', models.CharField(max_length=18, verbose_name='机构社会信用代码')),
                ('DepartInfo', models.TextField(max_length=255, verbose_name='机构简介')),
                ('DepartAddress', models.TextField(max_length=255, verbose_name='机构地址')),
            ],
            options={
                'verbose_name': '机构名称 ',
                'verbose_name_plural': '机构名称 ',
                'db_table': 'DepartName',
            },
        ),
        migrations.CreateModel(
            name='EnvManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnvManager', models.SmallIntegerField(choices=[(1, '生产环境'), (2, '测试环境'), (3, '开发环境')], verbose_name='环境')),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'EnvManager',
            },
        ),
        migrations.CreateModel(
            name='ServerPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortName', models.SmallIntegerField(choices=[(1, '映射端口'), (2, '服务端口')], verbose_name='端口服务')),
                ('PortNum', models.IntegerField(verbose_name='端口号')),
                ('PortType', models.SmallIntegerField(choices=[(1, 'TCP'), (2, 'UDP')], verbose_name='端口协议')),
            ],
            options={
                'verbose_name': '端口号 ',
                'verbose_name_plural': '端口号 ',
                'db_table': 'PortNum',
            },
        ),
        migrations.CreateModel(
            name='SystemServerName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SystemName', models.CharField(max_length=64, verbose_name='业务系统名称')),
                ('SystemServerEnv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.envmanager', verbose_name='对应环境')),
                ('SystemServerPort', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.serverport', verbose_name='服务端口')),
            ],
            options={
                'verbose_name': '业务系统名称 ',
                'verbose_name_plural': '业务系统名称 ',
                'db_table': 'SystemServerName',
            },
        ),
        migrations.CreateModel(
            name='IpManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IpField', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP地址')),
                ('IpType', models.SmallIntegerField(choices=[(1, '业务地址'), (2, '映射地址'), (3, '服务器地址')], verbose_name='类别')),
                ('IpEnv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.envmanager', verbose_name='环境')),
            ],
            options={
                'verbose_name': 'IP地址 ',
                'verbose_name_plural': 'IP地址 ',
                'db_table': 'IpField',
            },
        ),
        migrations.CreateModel(
            name='DepartSystemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.department', verbose_name='机构信息')),
                ('IpManager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.ipmanager')),
                ('ServerPort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.serverport')),
                ('SystemName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.systemservername')),
            ],
            options={
                'verbose_name': '机构业务系统名称 ',
                'verbose_name_plural': '机构业务系统名称 ',
                'db_table': 'Department_Name',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='DepartIp',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.ipmanager', verbose_name='业务IP地址'),
        ),
    ]
