# Generated by Django 4.1.1 on 2023-08-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envmanager',
            name='EnvManager',
            field=models.CharField(choices=[(1, '生产环境'), (2, '测试环境'), (3, '开发环境')], max_length=16, verbose_name='环境'),
        ),
    ]
