# Generated by Django 4.1.1 on 2023-08-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_alter_envmanager_envmanagername'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemServerName',
            new_name='BusinessServer',
        ),
        migrations.RenameField(
            model_name='businessserver',
            old_name='SystemName',
            new_name='BusinessName',
        ),
        migrations.RenameField(
            model_name='businessserver',
            old_name='SystemServerEnv',
            new_name='BusinessServerEnv',
        ),
        migrations.RenameField(
            model_name='businessserver',
            old_name='SystemServerPort',
            new_name='BusinessServerPort',
        ),
    ]
