# Generated by Django 4.1.1 on 2023-08-31 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_rename_systemservername_businessserver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessserver',
            name='BusinessServerEnv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.envmanager', verbose_name='环境'),
        ),
        migrations.AlterModelTable(
            name='businessserver',
            table='BusinessServer',
        ),
    ]
