# Generated by Django 4.1.1 on 2023-08-31 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_businessserver_businessserverenv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envmanager',
            name='EnvManagerName',
            field=models.SmallIntegerField(choices=[(1, '生产环境'), (2, '测试环境'), (3, '开发环境')], help_text=((1, '生产环境'), (2, '测试环境'), (3, '开发环境')), verbose_name='环境'),
        ),
    ]
