# Generated by Django 4.1.1 on 2023-08-31 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_envmanager_envmanagername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessserver',
            name='BusinessServerPort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.serverport', verbose_name='服务端口'),
        ),
    ]
