# Generated by Django 4.1.1 on 2023-08-31 02:24

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_alter_businessserver_businessserverport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessserver',
            name='BusinessServerEnv',
            field=models.CharField(choices=[('produce', '生产环境'), ('testing', '测试环境'), ('develop', '开发环境')], default=app01.models.EnvManager['produce'], max_length=16),
        ),
        migrations.AlterField(
            model_name='ipmanager',
            name='IpEnv',
            field=models.CharField(choices=[('produce', '生产环境'), ('testing', '测试环境'), ('develop', '开发环境')], default=app01.models.EnvManager['produce'], max_length=16),
        ),
        migrations.DeleteModel(
            name='EnvManager',
        ),
    ]
