# Generated by Django 4.1.1 on 2023-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_alter_businessserver_businessserverenv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmanager',
            name='IpType',
            field=models.SmallIntegerField(choices=[(1, '业务地址'), (2, '映射地址'), (3, '服务器地址')], verbose_name='类别'),
        ),
    ]
