# Generated by Django 4.1.1 on 2023-08-31 02:41

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_alter_ipmanager_iptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessserver',
            name='BusinessServerEnv',
            field=models.CharField(choices=[('生产环境', '生产环境'), ('测试环境', '测试环境'), ('开发环境', '开发环境')], default=app01.models.EnvManager['produce'], max_length=16, verbose_name='业务系统环境'),
        ),
    ]
